version: '3.8'

services:
  app:
    container_name: namoland-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    env_file:
      - .env
    environment:
      - PORT=3008
    volumes:
      - ./uploads:/app/public/uploads
